/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.*;
import Entidades.*;
import java.util.TreeSet;
import javax.swing.JOptionPane;

public class NuevoPJ extends javax.swing.JInternalFrame {
    
    int[] tiradas = new int[6];
    
    public NuevoPJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInfo = new javax.swing.JPanel();
        jcbRaza = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbClase = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtJugador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtPersonaje = new javax.swing.JTextField();
        jpBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jpStats = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jtTirada1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtTirada2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtTirada3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtTirada4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtTirada5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtTirada6 = new javax.swing.JLabel();

        jcbRaza.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel3.setText("Raza");

        jcbClase.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel4.setText("Clase");

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel1.setText("Jugador");

        jtJugador.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel2.setText("Personaje");

        jtPersonaje.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N

        javax.swing.GroupLayout jpInfoLayout = new javax.swing.GroupLayout(jpInfo);
        jpInfo.setLayout(jpInfoLayout);
        jpInfoLayout.setHorizontalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jcbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcbClase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jpInfoLayout.setVerticalGroup(
            jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jButton1.setText("Crear Personaje");

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        jButton2.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jButton2.setText("Roll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtTirada1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada1.setText("0");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel7.setText(" - ");

        jtTirada2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada2.setText("0");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel9.setText(" - ");

        jtTirada3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada3.setText("0");

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel11.setText(" - ");

        jtTirada4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada4.setText("0");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel13.setText(" - ");

        jtTirada5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada5.setText("0");

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel15.setText(" - ");

        jtTirada6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jtTirada6.setText("0");

        javax.swing.GroupLayout jpStatsLayout = new javax.swing.GroupLayout(jpStats);
        jpStats.setLayout(jpStatsLayout);
        jpStatsLayout.setHorizontalGroup(
            jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jtTirada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTirada2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTirada3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTirada4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTirada5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTirada6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpStatsLayout.setVerticalGroup(
            jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jtTirada1)
                    .addComponent(jLabel7)
                    .addGroup(jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtTirada2)
                        .addComponent(jLabel9)
                        .addGroup(jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTirada3)
                            .addComponent(jLabel11)
                            .addGroup(jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtTirada4)
                                .addComponent(jLabel13)
                                .addGroup(jpStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtTirada5)
                                    .addComponent(jLabel15)
                                    .addComponent(jtTirada6))))))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tirada;        
        
        for (int i = 0; i < tiradas.length; i++) {
            do {
                tirada = rollDice(3, 6);
            } while (tirada < 10);
            tiradas[i]=tirada;
        }
        
        jtTirada1.setText(""+tiradas[0]);
        jtTirada2.setText(""+tiradas[1]);
        jtTirada3.setText(""+tiradas[2]);
        jtTirada4.setText(""+tiradas[3]);
        jtTirada5.setText(""+tiradas[4]);
        jtTirada6.setText(""+tiradas[5]);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<Raza> jcbClase;
    private javax.swing.JComboBox<Raza> jcbRaza;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpInfo;
    private javax.swing.JPanel jpStats;
    private javax.swing.JTextField jtJugador;
    private javax.swing.JTextField jtPersonaje;
    private javax.swing.JLabel jtTirada1;
    private javax.swing.JLabel jtTirada2;
    private javax.swing.JLabel jtTirada3;
    private javax.swing.JLabel jtTirada4;
    private javax.swing.JLabel jtTirada5;
    private javax.swing.JLabel jtTirada6;
    // End of variables declaration//GEN-END:variables

    public int rollDice(int cantidad, int caras) {
        int roll = 0;
        int random;

        if (cantidad < 0 || caras < 0) {
            JOptionPane.showMessageDialog(null, "Error en la tirada");
        } else {
            for (int i = 0; i < cantidad; i++) {
                random = (int) (Math.random() * caras) + 1;
                roll += random;
            }
        }

        return roll;
    }
}
