/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Planilla
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpInterfaz = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmNuevopj = new javax.swing.JMenuItem();
        jmPlanilla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpInterfazLayout = new javax.swing.GroupLayout(jdpInterfaz);
        jdpInterfaz.setLayout(jdpInterfazLayout);
        jdpInterfazLayout.setHorizontalGroup(
            jdpInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );
        jdpInterfazLayout.setVerticalGroup(
            jdpInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jMenu2.setText("Personajes");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmNuevopj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmNuevopj.setText("Nuevo Personaje");
        jmNuevopj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevopjActionPerformed(evt);
            }
        });
        jMenu2.add(jmNuevopj);

        jmPlanilla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmPlanilla.setText("Planilla");
        jmPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPlanillaActionPerformed(evt);
            }
        });
        jMenu2.add(jmPlanilla);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpInterfaz)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpInterfaz)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPlanillaActionPerformed
        jdpInterfaz.removeAll();
        jdpInterfaz.repaint();
        Info planilla = new Info();
        planilla.setVisible(true);
        jdpInterfaz.add(planilla);
        jdpInterfaz.moveToFront(planilla);
    }//GEN-LAST:event_jmPlanillaActionPerformed

    private void jmNuevopjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevopjActionPerformed
        jdpInterfaz.removeAll();
        jdpInterfaz.repaint();
        NuevoPJ nuevopj = new NuevoPJ();
        nuevopj.setVisible(true);
        jdpInterfaz.add(nuevopj);
        jdpInterfaz.moveToFront(nuevopj);
    }//GEN-LAST:event_jmNuevopjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpInterfaz;
    private javax.swing.JMenuItem jmNuevopj;
    private javax.swing.JMenuItem jmPlanilla;
    // End of variables declaration//GEN-END:variables
}
